<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IdentityHub.Domain\IdentityHub.Domain.csproj" />
    <ProjectReference Include="..\IdentityHub.Shared\IdentityHub.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mappings\" />
    <Folder Include="Validators\" />
  </ItemGroup>

</Project>
